language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script: coverage run manage.py test --settings=festos.test_settings --verbosity=2
after_success:
  - coveralls
