language: python
python:
  - "2.7"
env:
  - DJANGO="1.7.2"
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO
  - pip install coverage
  - pip install coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mkdir /tmp/media"
script: coverage run manage.py test --settings=festos.test_settings --verbosity=2
after_success:
  - coveralls
after_script:
  - "sh -e /etc/init.d/xvfb stop"
